name: nextjs-task

services:
  postgres:
    image: postgres:15
    container_name: nextjs-task-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - nextjs-task-db-data:/var/lib/postgresql/data
      - ./build/local/docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  web:
    build:
      context: ./frontend
      target: runner
    container_name: nextjs-task-web
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
      NODE_ENV: production
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  nextjs-task-db-data:
